version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: project-mongo
    volumes:
      - project_mongo_data:/data/db
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_PASSWORD}

volumes:
  project_mongo_data: